SELECT ROUND(SUM(TIV_2016),2) AS TIV_2016
FROM insurance
WHERE (LAT, LON) IN 
(SELECT LAT, LON FROM insurance
GROUP BY LAT, LON HAVING COUNT(*) = 1)
AND TIV_2015 IN (SELECT TIV_2015 FROM insurance GROUP BY TIV_2015 HAVING COUNT(*) >= 2);